export const MERGE_ONE_SEARCH_USER = "MERGE_ONE_SEARCH_USER";
export const MERGE_SEARCH_USERS = "MERGE_SEARCH_USERS";
export const SET_ONE_SEARCH_USER = "SET_ONE_SEARCH_USER";
export const SET_SEARCH_USERS = "SET_SEARCH_USERS";
export const RECEIVE_SEARCH_USER_ERRORS = "RECEIVE_SEARCH_USER_ERRORS";